[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
tag_format = "v$version"
version_files = [
    "pyproject.toml:version",
    "VERSION"
]
bump_message = "release $current_version → $new_version [skip ci]"
update_changelog_on_bump = true

[tool.codespell]
skip = "*.lock,*.cjs"
ignore-words-list = "ignored-word"
