default_language_version:
    python: python3
exclude: "^\
  (third_party/.*)\
  "
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: no-commit-to-branch
        args: ['--branch=master']
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: end-of-file-fixer
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        exclude: README.md
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        additional_dependencies: ['types-requests==2.31.0.1']
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
